import type { Snippet } from 'svelte';
type OptionType = string | number | Record<string, unknown>;
type $$ComponentProps = {
    value?: unknown;
    options?: OptionType[];
    label?: string;
    placeholder?: string;
    disabled?: boolean;
    readonly?: boolean;
    required?: boolean;
    error?: string;
    helperText?: string;
    size?: 'sm' | 'md' | 'lg';
    variant?: 'outlined' | 'filled' | 'standard';
    multiple?: boolean;
    clearable?: boolean;
    freeSolo?: boolean;
    valueKey?: string;
    labelKey?: string;
    filterOptions?: ((options: OptionType[], query: string) => OptionType[]) | null;
    noOptionsText?: string;
    minSearchLength?: number;
    onchange?: (value: unknown) => void;
    oninputchange?: (query: string) => void;
    onfocus?: (event: FocusEvent) => void;
    onblur?: (event: FocusEvent) => void;
    option?: Snippet<[OptionType]>;
    noOptions?: Snippet;
};
declare const Autocomplete: import("svelte").Component<$$ComponentProps, {}, "value">;
type Autocomplete = ReturnType<typeof Autocomplete>;
export default Autocomplete;
